baseurl: /tacoma
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: tacoma
github_org: maptime
maptime:
  chapter: MaptimeTacoma
  #twitter: MaptimeTacoma
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
